import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/components/ui/modetoggle";
import { Button } from "@/components/ui/button";
import { GoArrowRight } from "react-icons/go";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange>

        <div className="flex justify-between mt-2 mb-2">
          {/*<div className="col-start-7 ml-8 mt-2"><h1 className="">F1</h1></div>*/}
          <div className="ml-4"><ModeToggle></ModeToggle></div>
          <div className="mr-4"><Button variant="outline"><GoArrowRight></GoArrowRight></Button></div>
        </div>
        
        <Separator />
        {children}
        </ThemeProvider>
      </body>
     
    </html>
  );
}