import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Separator } from "@/components/ui/separator";
import { ModeToggle } from "@/components/ui/modetoggle";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange>

        <div className="grid grid-cols-4 gap-1">
          <br />
          <h2>hello</h2>
          <h2>hello</h2>
          <ModeToggle></ModeToggle>
        </div>
        <Separator />
        <br />
        {children}

      </ThemeProvider>
      </body>
    </html>
  );
}